name: discord_bot
description: Discord bot for the dahliaOS server
version: 0.0.1
homepage: https://dahliaos.io/discord

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  nyxx: ^2.0.0-rc.10
  nyxx_commander: ^2.0.0-rc.10
  moor: ^4.4.1

dev_dependencies:
  build_runner:
  moor_generator:
  pedantic:
  test:
