name: discord_bot
description: Discord bot for the dahliaOS server
version: 0.0.1
homepage: https://dahliaos.io/discord
repository: https://github.com/dahliaOS/bot
issue_tracker: https://github.com/dahliaOS/bot/issues

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  nyxx: ^2.0.0-rc.10
  nyxx_commander: ^2.0.0-rc.10
  moor: ^4.4.1
  dotenv: ^3.0.0
  http: ^0.13.3

dev_dependencies:
  build_runner: ^2.0.6
  moor_generator: ^4.4.1
  pedantic: ^1.11.1
  test: ^1.17.10
